name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: chrvadala/github-actions/.github/workflows/test-nodejs.yml@v2
    permissions:
      contents: read
      statuses: write
    with:
      node-versions: '[24, 26]'